version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "omer3kale"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    
  # Frontend dependencies (if package.json exists in future)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "omer3kale"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    
  # PayPal Standard dependencies
  - package-ecosystem: "npm"
    directory: "/paypalstandard/standard/client/html"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "paypal"
    commit-message:
      prefix: "⬆️"
      
  - package-ecosystem: "npm"
    directory: "/paypalstandard/standard/server/node"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "paypal"
    commit-message:
      prefix: "⬆️"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "⬆️"
