[build]
  publish = "frontend"
  functions = "netlify/functions"
  command = "echo 'No build needed'"

[build.environment]
  NODE_VERSION = "20"

[dev]
  publish = "frontend"
  functions = "netlify/functions"
  framework = "#static"

# Custom Domain Redirects - Normalize apex → www and force HTTPS
# IMPORTANT: Set Primary domain in Netlify to "www.sichrplace.com" to avoid loops

# Apex (sichrplace.com) → www
[[redirects]]
  from = "/*"
  to = "https://www.sichrplace.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["sichrplace.com"] }

# http → https for www
[[redirects]]
  from = "http://www.sichrplace.com/*"
  to = "https://www.sichrplace.com/:splat"
  status = 301
  force = true

# API redirects - route API calls to Netlify Functions
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/simple-health"
  to = "/.netlify/functions/simple-health"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/api/paypal-config"
  to = "/.netlify/functions/paypal-config"
  status = 200

[[redirects]]
  from = "/api/csrf-token"
  to = "/.netlify/functions/csrf-token"
  status = 200

[[redirects]]
  from = "/api/viewing-request"
  to = "/.netlify/functions/viewing-request"
  status = 200

[[redirects]]
  from = "/api/send-message"
  to = "/.netlify/functions/send-message"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# TEMPORARILY REMOVED: Catch-all redirect to test functions
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = false

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Enhanced Security Headers for www.sichrplace.com
[[headers]]
  for = "/*"
  [headers.values]
    # Core Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HSTS (HTTP Strict Transport Security) - Force HTTPS for 1 year
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy - Enhanced security
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://js.stripe.com https://www.paypal.com https://www.sandbox.paypal.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://api.stripe.com https://api.paypal.com https://api.sandbox.paypal.com https://*.supabase.co wss://*.supabase.co; frame-src 'self' https://js.stripe.com https://www.paypal.com https://www.sandbox.paypal.com; object-src 'none'; base-uri 'self'; form-action 'self';"
    
    # Permissions Policy (Feature Policy replacement)
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=(self)"
    
    # Additional Security Headers
    X-Permitted-Cross-Domain-Policies = "none"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-CSRF-Token"

# Cache static assets
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
