[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = { default = "production" }
PORT = { default = "3000" }

[[services]]
name = "backend"

[services.healthcheck]
path = "/api/health"
timeout = 30
