name: 🔒 Security Audit

on:
  schedule:
    # Run security audit every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-audit:
    name: 🔍 Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: ⚡ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: 📦 Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: 🔍 Run npm audit
      run: |
        cd backend
        npm audit --audit-level moderate
        
    - name: 🔒 Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=medium
        
    - name: 📊 Upload Snyk results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: snyk.sarif
